# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

stages:
- stage: Build
  variables:
    BuildConfiguration: release
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: '**/*.json'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: '$(build.artifactstagingdirectory)'

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: deploy
    displayName: Deploy job
    environment: 'myFirstEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'drop'

          - task: AzureAppServiceManage@0
            inputs:
              ConnectedServiceName: 'Visual Studio Enterprise(84261ad2-9073-4045-8bd1-f2f859e0b0c1)'
              Action: 'Stop Azure App Service'
              WebAppName: 'vssummit2019'   

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectedServiceName: 'Visual Studio Enterprise(84261ad2-9073-4045-8bd1-f2f859e0b0c1)'
              WebAppName: 'vssummit2019'
              Package: '$(System.ArtifactsDirectory)/**/*.zip'

          - task: AzureAppServiceManage@0
            inputs:
              ConnectedServiceName: 'Visual Studio Enterprise(84261ad2-9073-4045-8bd1-f2f859e0b0c1)'
              Action: 'Start Azure App Service'
              WebAppName: 'vssummit2019'
          
